library(rvest)
library(dplyr)
library(robotstxt)
library(stringr)
link<-"https://www.flipkart.com/mobile-accessories/power-banks/pr?sid=tyy%2C4mr%2Cfu6&otracker=categorytree&otracker=nmenu_sub_Electronics_0_Power+Banks&fm=neo%2Fmerchandising&iid=M_1e0067bf-7027-4d80-850f-400349df25a7_1_372UD5BXDFYS_MC.SUDNEM7MT757&otracker=hp_rich_navigation_10_1.navigationCard.RICH_NAVIGATION_Electronics%7EPowerbank_SUDNEM7MT757&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_10_L1_view-all&cid=SUDNEM7MT757&p%5B%5D=facets.capacity%255B%255D%3D10000%2B-%2B12999%2BmAh"
path=paths_allowed(link)
web<-read_html(link)
name<-web %>% html_nodes(".s1Q9rs") %>% html_text()
View(name)
price<-web %>% html_nodes("._30jeq3") %>% html_text()
View(price)
discount<-web %>% html_node("._3Ay6Sb span") %>% html_text()
View(discount)
originalprice<-web %>% html_node("._3I9_wc") %>% html_text()
View(originalprice)
rakshana.us<- data.frame(name,price,discount,originalprice)
View(rakshana.us)
write.csv(rakshana.us,"power_bank.csv")
